CREATE TABLE public.workday_icims (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  domain text,
  role_searched text,
  source_ats text,
  company text,
  job_id text,
  title text,
  job_url text UNIQUE,
  description text,
  location text,
  city text,
  state text,
  country text,
  department text,
  job_category text,
  employment_type text,
  time_type text,
  posted_date text,
  salary text,
  experience_level text,
  company_logo text,
  remote_eligible text,
  scraped_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workday_icims_pkey PRIMARY KEY (id)
);
